import type { MetadataRoute } from "next";

/**
 * Web app manifest — drives Android's "Add to Home Screen".
 *
 * `short_name` is what actually shows under the icon on a home screen (`name` is used in
 * install prompts and the app list), so both are the compact "FBB Sim"; the browser tab
 * keeps the full title from layout.tsx. iOS reads none of this for the home-screen label —
 * that comes from `apple-mobile-web-app-title`, set via `appleWebApp.title` in layout.tsx,
 * and the icon from app/apple-icon.png. Both halves have to stay in sync.
 *
 * Icons are regenerated by scripts/make_icons.py.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "FBBSim",
    short_name: "FBBSim",
    description:
      "Monte Carlo simulation and live category win probability for an ESPN fantasy basketball league.",
    start_url: "/",
    display: "standalone",
    background_color: "#F4F3EF",
    theme_color: "#F4F3EF",
    /*
     * Declared BOTH ways from the same files.
     *
     * "any" is the plain icon. "maskable" tells Android it may crop these to whatever
     * adaptive shape the launcher uses (circle, squircle, teardrop) instead of shrinking
     * the icon and dropping it inside a white blob of its own — which is what a manifest
     * with no maskable entry gets you.
     *
     * The same PNGs can serve both because the mark already sits inside the maskable safe
     * zone: the ball is 78% of the canvas (scripts/make_icons.py), and the spec's safe
     * area is the middle 80%. Keep that number at or under 80% or the crop will start
     * clipping the ball.
     */
    icons: [
      { src: "/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
      { src: "/icon-192.png", sizes: "192x192", type: "image/png", purpose: "maskable" },
      { src: "/icon-512.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
    ],
  };
}
