"""
Regenerate assets/touch_icon.py — the basketball home-screen icon (apple-touch-icon).

Why redrawn: the previous version's seam arcs extended past the ball's circle toward the
canvas edges ("eye" shape), sitting flush with almost no margin. iOS applies its own
squircle mask/crop to home-screen icons, and with so little safe margin that cropping made
the seam lines look disconnected from the circle ("lines don't match up with the circle").
This version keeps every seam arc anchored ON the circle's own boundary, with generous
margin on all sides, so OS-level masking can't visually separate them.

    pip install pillow
    python assets/make_touch_icon.py    # run from the repo root
"""
import base64
import io
import os

from PIL import Image, ImageDraw

HERE = os.path.dirname(os.path.abspath(__file__))
SIZE = 180
MARGIN = 26                       # safe margin on all sides before OS cropping/masking
ORANGE = (224, 106, 59)           # --clay (matches the app's accent palette)
INK = (27, 29, 34)                # --ink
WHITE = (255, 255, 255)


def main():
    img = Image.new("RGB", (SIZE, SIZE), WHITE)
    d = ImageDraw.Draw(img)

    r = (SIZE - 2 * MARGIN) // 2
    cx = cy = SIZE // 2
    bbox = (cx - r, cy - r, cx + r, cy + r)

    line_w = max(3, r // 18)
    d.ellipse(bbox, fill=ORANGE, outline=INK, width=line_w)

    # Vertical + horizontal seams (full diameter, clipped to the circle by construction).
    d.line((cx, cy - r, cx, cy + r), fill=INK, width=line_w)
    d.line((cx - r, cy, cx + r, cy), fill=INK, width=line_w)

    # Two curved side seams, anchored on the circle boundary (top/bottom), bowing inward -
    # unlike the old design, these never leave the circle's own silhouette.
    curve_bbox_left = (cx - r * 1.7, cy - r, cx - r * 0.3, cy + r)
    curve_bbox_right = (cx + r * 0.3, cy - r, cx + r * 1.7, cy + r)
    d.arc(curve_bbox_left, start=300, end=60, fill=INK, width=line_w)
    d.arc(curve_bbox_right, start=120, end=240, fill=INK, width=line_w)

    buf = io.BytesIO()
    img.save(buf, format="PNG")
    b64 = base64.b64encode(buf.getvalue()).decode()

    module = (
        '"""\n'
        "Apple/Android home-screen icon (basketball mark), generated by make_touch_icon.py.\n"
        "Streamlit's own index.html ships a Streamlit-branded apple-touch-icon that page_icon\n"
        "does not override, so Add to Home Screen on iOS showed the Streamlit logo instead of\n"
        "the app's. Injected via JS (see streamlit_app.py) as a <link rel=apple-touch-icon> in\n"
        "<head>. Opaque background (no alpha) with a generous margin around the design, since\n"
        "iOS applies its own squircle mask/crop to home-screen icons - a design with little\n"
        "margin or transparency gets visually cropped/misaligned by that masking.\n"
        '"""\n\n'
        f"TOUCH_ICON_PNG_B64 = (\n"
    )
    # wrap the b64 string across lines like the original, for readability
    chunk = 96
    lines = [f'    "{b64[i:i+chunk]}"' for i in range(0, len(b64), chunk)]
    module += "\n".join(lines) + "\n)\n"

    open(os.path.join(HERE, "touch_icon.py"), "w", encoding="utf-8").write(module)
    print(f"wrote assets/touch_icon.py ({len(b64)} b64 chars)")


if __name__ == "__main__":
    main()
