"""
Apple/Android home-screen icon (basketball mark), generated by make_touch_icon.py.
Streamlit's own index.html ships a Streamlit-branded apple-touch-icon that page_icon
does not override, so Add to Home Screen on iOS showed the Streamlit logo instead of
the app's. Injected via JS (see streamlit_app.py) as a <link rel=apple-touch-icon> in
<head>. Opaque background (no alpha) with a generous margin around the design, since
iOS applies its own squircle mask/crop to home-screen icons - a design with little
margin or transparency gets visually cropped/misaligned by that masking.
"""

TOUCH_ICON_PNG_B64 = (
    "iVBORw0KGgoAAAANSUhEUgAAALQAAAC0CAIAAACyr5FlAAAF8klEQVR4nO2dQW7bMBBFXcGXKBBkk2PwDD1tzqBjZBMYyDHS"
    "hQFDsDSybInDP8P3VkXStOTk+c+QTuw/v7+/J4AlhsWPAiAHrEFygAlygAlygAlygAlygAlygAlygAlygAlygAlygAlygAly"
    "gAlygAlygAlygAlygAlygAlygAlygAlygAlygAlygAlygMn51Ctv7x/b//Ll++vUH386+XXIp1TYwqUDXTLLcbgQvYmSUI6N"
    "Toz//t59pHz+PPxUV5acO3Fi/v1+inGbLrc15LDknFiLnUKsM/3H56JclxRdkcByNHFi/X+8syR6kJzTaOHvxLOWhFPknMAM"
    "BS0WlzRXJJYfWnKs53AILdYVWYkQQXW0jrLTb/+0Uj5arBxl9zMfWhc3KOWH1nMri/W6M2P891c8MBaZL9vaoA5ayfGwWFW1"
    "qJocD+/TpDJDcea4cvn+Cjde7JxVBc2QaysWacy4YbUYKRTl0KzUsViXqlLIyTGtkXWnFJ0y2c40QtT8GPTNSOZHmZkh64fK"
    "aWWjFplOK+PqM70KI+ogbkayabSs+qcWIRJyPPQgx/BRNixe6pHQXo7bQ2RjXUL7sWWnt882D48hihlSD6naA42IH0OgzIjb"
    "XMrzC1bwo5kczTOzCeNL+deqVoPg8SRZeJRXT8jNDy+NZ47ok0Tu+gz6o0bo8Ci7L9YaDh/ecvQ5agSt3hBi1AgaHuWg+/hW"
    "w0ebmYNRI0TF/OQ4Vnn98CjVFuYWHg2So7fYGA/ar3/dhhAnFGhycvGQo9JOlDtLqf+jIQ5+uLYVYiNWDavL4ROAUuFRvBZT"
    "u7ZDaOXFo2isszy3Xbf/YR+QZUhzSJHqLDmOLeGTQ62zFJcfYfehohzcbUQPj/DJAfXIIIfObVhpvYAYcnTeU0aXXdfuLBmS"
    "AyqBHOArR+c9xZOqnSVJcijMpCXRDUcqOaAGyAGOcjBwpBk7SA4wQQ4wQQ7oQI62p9mS7hybSg5Ql4OjSqYDC8kBJsgBJsgB"
    "JsgBJsgBXi+Mz6s6NefAV9QnOcAEOcD9DQCb3CLvvMPe8+Wl9fV5jScNSA4wQQ4wQQ4wQQ4wQQ7wkuN2A5PsV4rFuVX72PeU"
    "JDmgAzna3jSMAr9ydzh55IDDQQ4wQQ5wlIMDS46jCskBa9BWILsczZ8xP2U8zVaRg7EjwcCRJzmgBsgB7nJ03lmKy66r9pQk"
    "yaEwjYos4FgyyAHx5Oi8s0TvKRmSQ828MdFtR105PMMjWb9vHhsZkgMyyFEjPMSju9RZntuuq8tRNfc0e8rotZjatXVtK+IP"
    "9BB41nCIK7jO3VeTM4tDJDslB3cegQ4pLU8rvTWXctB+/evmJ8exsiv3lNoL84mNZvccvYVH0Iq5yjFVfs9u9WPj2LF0+uVu"
    "sdEgOTz3lo+Lb/UatJWdJ5cosXFUeDifUISeW2H4UK5PGzleHj5ixcbO8Gg1arRPjj6Hj/JSErSqVcu28uzwETE29r+wacNH"
    "UeOZY7sf0aeT8ZnmomBGezleyI9wsTFnfaciZkjIsaVqcRvKlC2LlwpICTnWDy9S9araXJofT5xeGP9ZrrW4vl3LtUbXOk7r"
    "FTo25pTPn0VXFLQQSo4tEZLGjHGykeseNc2Qk8PyI40Zlh+CZijKIVijGsx1F9y1ohxzMs2kizsSNENoIH34LoLTKTU0ZUn0"
    "t/cPQT8GZTMu3193JYseIWUWGLcNvr1/qL235qBsxt0frpTPn4iKlNmyrQ3qoNhW5vWa3oKE6zJlpvLchsv3l2BnOfhNhx2Y"
    "Z+9Rihx+ci4btFBGNDlWuD7Iph8RTJGy1PhimRFSjsUuI3JjVoxhKJwWgeW4Mp3z21pScjmRQY71IKn9pF1ZPTFF1yKPHOtB"
    "Yn0vn9KlbDs853Ai8GllO253SpdcTnQhR1VRLkmF6FGOnbpcOlBhTr9yQLDnVkAK5AAT5AAT5AAT5AAT5AAT5AAT5AAT5AAT"
    "5AAT5AAT5AAT5AAT5AAT5AAT5AAT5AAT5AAT5AAT5AAT5AAT5AAT5AAT5ICTxX9PihGPREUMkAAAAABJRU5ErkJggg=="
)
