"""
Regenerate assets/icon_font.py — the self-hosted, subset Bootstrap Icons font.

Why this exists: a CDN `@import` at the top of the stylesheet is render-blocking, so a
slow/blocked CDN once stopped the whole custom stylesheet from applying (the header lost
its brand, icons, and gear, and Streamlit's default decoration bar showed). We fix that by
embedding the font — subset to only the ~few dozen `bi-*` glyphs the app actually uses — as
a base64 `@font-face`. Run this whenever you add/remove a `bi-*` icon class.

    pip install fonttools brotli        # brotli is needed to (de)compress woff2
    python assets/build_icon_font.py    # run from the repo root

It scans the app for `bi-*` classes, downloads Bootstrap Icons 1.11.0, subsets the woff2 to
those glyphs, and writes assets/icon_font.py (ICON_FONT_CSS: @font-face + per-class `content`).
"""
import base64
import io
import os
import re
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))   # this assets/ folder
ROOT = os.path.dirname(HERE)                         # repo root (where the app lives)
VERSION = "1.11.0"
BASE = f"https://cdn.jsdelivr.net/npm/bootstrap-icons@{VERSION}/font/"
# app files (in the repo root) scanned for `bi-*` usage (exclude Old Models/ — historical)
SOURCES = ["streamlit_app.py", "styles.py", "visualizations.py", "data.py", "simulation.py"]


def collect_used():
    used = set()
    for f in SOURCES:
        p = os.path.join(ROOT, f)
        if os.path.exists(p):
            used |= set(re.findall(r"bi-[a-z0-9-]+", open(p, encoding="utf-8").read()))
    used.discard("bi-")
    return used


def main():
    from fontTools.subset import Options, Subsetter
    from fontTools.ttLib import TTFont

    used = collect_used()
    css = urllib.request.urlopen(BASE + "bootstrap-icons.css", timeout=30).read().decode()
    cp = {m.group(1): int(m.group(2), 16)
          for m in re.finditer(r"\.(bi-[a-z0-9-]+)::before\s*\{\s*content:\s*\"\\([0-9a-fA-F]+)\"", css)}
    missing = sorted(c for c in used if c not in cp)
    if missing:
        print("WARNING: no codepoint for:", missing)
    used = sorted(c for c in used if c in cp)
    print(f"{len(used)} icons used")

    woff2 = urllib.request.urlopen(BASE + "fonts/bootstrap-icons.woff2", timeout=30).read()
    font = TTFont(io.BytesIO(woff2))
    opt = Options()
    opt.flavor = "woff2"
    opt.desubroutinize = True
    ss = Subsetter(options=opt)
    ss.populate(unicodes={cp[c] for c in used})
    ss.subset(font)
    buf = io.BytesIO()
    font.flavor = "woff2"
    font.save(buf)
    b64 = base64.b64encode(buf.getvalue()).decode()
    print(f"subset woff2: {buf.tell()} bytes ({len(b64)} b64 chars)")

    lines = [
        "    @font-face {",
        "        font-family: 'bootstrap-icons';",
        "        font-display: block;",
        f"        src: url('data:font/woff2;base64,{b64}') format('woff2');",
        "    }",
        '    .bi::before, [class^="bi-"]::before, [class*=" bi-"]::before {',
        "        display: inline-block;",
        '        font-family: "bootstrap-icons" !important;',
        "        font-style: normal; font-weight: normal !important; font-variant: normal;",
        "        text-transform: none; line-height: 1; vertical-align: -0.125em;",
        "        -webkit-font-smoothing: antialiased; -moz-osx-font-smoothing: grayscale;",
        "    }",
    ]
    lines += [f'    .{c}::before {{ content: "\\{cp[c]:x}"; }}' for c in used]
    body = "\n".join(lines)
    assert "'''" not in body and not body.endswith("\\")

    module = (
        '"""\n'
        "Embedded Bootstrap Icons (v" + VERSION + "), subset to only the glyphs this app uses.\n"
        "GENERATED by assets/build_icon_font.py — do not edit by hand; rerun that script instead.\n"
        "Self-hosted on purpose: a CDN @import is render-blocking, so embedding the font keeps\n"
        "`.bi` icons working offline and stops a slow asset from blocking the layout stylesheet.\n"
        '"""\n\n'
        "# raw string: CSS unicode escapes (\\fXXXX) stay literal.\n"
        "ICON_FONT_CSS = r'''\n" + body + "\n'''\n"
    )
    open(os.path.join(HERE, "icon_font.py"), "w", encoding="utf-8").write(module)
    print("wrote assets/icon_font.py")


if __name__ == "__main__":
    main()
