"""
Write .env.local for the Next.js app from the credentials the Python side already has.

The web app reads ESPN_LEAGUE_ID / ESPN_SEASON_YEAR / ESPN_S2 / ESPN_SWID from the
environment (app/api/live). Locally those already exist in engine/config_secrets.py, so
generate the env file from there rather than making anyone copy cookies around by hand.

.env.local is gitignored (`.env*.local`) and is never bundled into the client - only
server-side route handlers can read it.

Run:  python scripts/make_env.py
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "engine"))

for _s in (sys.stdout, sys.stderr):
    try:
        _s.reconfigure(encoding="utf-8", errors="replace")
    except (AttributeError, ValueError):
        pass


def main() -> int:
    try:
        import config
    except Exception as exc:  # noqa: BLE001
        print(f"Could not import engine/config.py: {exc}")
        print("Local dev needs engine/config_secrets.py (copy config_secrets.example.py).")
        return 1

    values = {
        "ESPN_LEAGUE_ID": str(config.ESPN_LEAGUE_ID),
        "ESPN_SEASON_YEAR": str(config.ESPN_SEASON_YEAR),
        "ESPN_S2": str(config.ESPN_S2 or ""),
        "ESPN_SWID": str(config.ESPN_SWID or ""),
        # Powers the Agent chat page (app/api/agent). Optional: without it every other
        # page still works and only /agent reports that the key is missing.
        "GEMINI_API_KEY": str(getattr(config, "GEMINI_API_KEY", "") or ""),
        # The free-tier fallback chain, so the web app rotates models exactly as the
        # Streamlit assistant does. lib/gemini.ts has the same list as its default.
        "GEMINI_MODELS": ",".join(getattr(config, "GEMINI_MODELS", []) or []),
    }
    espn_missing = [k for k, v in values.items() if not v and k.startswith("ESPN_")]
    if espn_missing:
        print(f"! empty in config: {', '.join(espn_missing)} — /api/live will return 500")
    if not values["GEMINI_API_KEY"]:
        print("! GEMINI_API_KEY empty in config — the Agent page will be disabled")

    out = ROOT / ".env.local"
    body = (
        "# Generated by scripts/make_env.py — do not commit (gitignored).\n"
        "# Server-side only: read by app/api/live and app/api/agent, never bundled\n"
        "# into the browser.\n"
        + "".join(f"{k}={v}\n" for k, v in values.items())
    )
    out.write_text(body, encoding="utf-8")

    # Never echo the cookie or key values themselves.
    plain = ("ESPN_LEAGUE_ID", "ESPN_SEASON_YEAR", "GEMINI_MODELS")
    print(f"wrote {out}")
    for k, v in values.items():
        shown = v if k in plain else ("set" if v else "EMPTY")
        print(f"  {k:<18} {shown}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
